from __future__ import annotations

from ffbb_mcp._state import _read_positive_int_env
from ffbb_mcp.cache_strategy import get_static_ttl

from .club import (
    _dedup_equipes_by_engagement,
    _fetch_poule_matches,
    _prioritize_phase,
    _resolve_team_equipes,
    ffbb_bilan_service,
    ffbb_equipes_club_service,
    ffbb_head_to_head_service,
    ffbb_last_result_service,
    ffbb_next_match_service,
    ffbb_saison_bilan_service,
    get_calendrier_club_service,
)
from .common import (
    _MAX_CALENDAR_MATCHES,
    _MAX_CONCURRENT_FFBB,
    _cache_hit_hook,
    _cache_miss_hook,
    _dedupe_inflight,
    _get_inflight_lock,
    disambiguate_clubs_by_category,
    get_cache_ttls,
    get_client_async,
    handle_api_error,
)
from .poule import (
    ffbb_get_classement_service,
    find_team_poule_service,
    format_poule_response,
    get_competition_service,
    get_engagement_service,
    get_lives_service,
    get_organisme_service,
    get_poule_service,
    get_saisons_service,
    resolve_opponent_from_poule,
)
from .regulations import (
    explain_tiebreak_rules_service,
    get_regulation_article_service,
    list_regulations_service,
    search_regulations_service,
)
from .salle import get_salle_service
from .search import (
    _extract_club_key_word,
    ffbb_search_service,
    filter_inactive_ententes,
    get_entraineur_service,
    get_officiel_service,
    get_rencontre_service,
    multi_search_service,
    resolve_club_and_org,
    resolve_poule_id_service,
    search_organismes_service,
)
from .team_resolver import (
    ffbb_find_team_candidates_service,
    ffbb_resolve_team_service,
)
from .warmup import warmup_cache_service

__all__ = [
    "_MAX_CALENDAR_MATCHES",
    "_MAX_CONCURRENT_FFBB",
    "_cache_hit_hook",
    "_cache_miss_hook",
    "_dedup_equipes_by_engagement",
    "_dedupe_inflight",
    "_extract_club_key_word",
    "_fetch_poule_matches",
    "_get_inflight_lock",
    "_prioritize_phase",
    "_read_positive_int_env",
    "_resolve_team_equipes",
    "disambiguate_clubs_by_category",
    "explain_tiebreak_rules_service",
    "ffbb_bilan_service",
    "ffbb_equipes_club_service",
    "ffbb_find_team_candidates_service",
    "ffbb_get_classement_service",
    "ffbb_head_to_head_service",
    "ffbb_last_result_service",
    "ffbb_next_match_service",
    "ffbb_resolve_team_service",
    "ffbb_saison_bilan_service",
    "ffbb_search_service",
    "filter_inactive_ententes",
    "find_team_poule_service",
    "format_poule_response",
    "get_cache_ttls",
    "get_calendrier_club_service",
    "get_client_async",
    "get_competition_service",
    "get_engagement_service",
    "get_entraineur_service",
    "get_lives_service",
    "get_officiel_service",
    "get_organisme_service",
    "get_poule_service",
    "get_regulation_article_service",
    "get_rencontre_service",
    "get_saisons_service",
    "get_salle_service",
    "get_static_ttl",
    "handle_api_error",
    "list_regulations_service",
    "multi_search_service",
    "resolve_club_and_org",
    "resolve_opponent_from_poule",
    "resolve_poule_id_service",
    "search_organismes_service",
    "search_regulations_service",
    "warmup_cache_service",
]
